{% set name = "tensorstore" %}
{% set version = "0.1.54" %}
# Bazel version is specified upstream, file .bazelversion
# https://github.com/google/tensorstore/blob/master/.bazelversion
{% set bazel_version = "6.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tensorstore-{{ version }}.tar.gz
  sha256: e1a9dcb0be7c828f752375409537d4b39c658dd6c6a0873fe21a24a556ec0e2a
  patches:
    # MacOS needs an extra linker flag so pybind11 finds the python symbols in _tensorstore.so :shrug:
    - patches/pybind11-linkopts.patch  # [osx]

build:
  skip: true  # [py<=38 or win]
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # Keep bazel listed twice here to help the migrators track dependencies
    - bazel
    - bazel {{ bazel_version }}
    - bazel-toolchain
    - pip  # [target_platform != build_platform]
    - python  # [target_platform != build_platform]
    - wheel  # [target_platform != build_platform]
    - setuptools-scm  # [target_platform != build_platform]
    - numpy  # [target_platform != build_platform]
    - pybind11  # [target_platform != build_platform]
    - pybind11-abi  # [target_platform != build_platform]
  host:
    - pip
    - python
    - wheel
    - setuptools-scm
    - numpy
    # we use openssl instead of boringssl
    - openssl
    - bzip2
    - blosc
    - libcurl
    - libjpeg-turbo
    - libpng
    - lz4
    - xz
    - zlib
    - libprotobuf
    # unvendored
    - pybind11
    - pybind11-abi
    # Use the one from https://github.com/google/tensorstore/blob/master/third_party/com_github_nlohmann_json/workspace.bzl
    - nlohmann_json 3.10.5
    - libavif
    # needs to be built with bazel
    # https://github.com/abseil/abseil-cpp/blob/ee0ebda/FAQ.md#what-is-abi-and-why-dont-you-recommend-using-a-pre-compiled-version-of-abseil
    # - abseil-cpp
  run:
    - ml_dtypes
    - {{ pin_compatible('numpy') }}
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - tensorstore
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tensorstore/
  summary: Read and write large, multi-dimensional arrays
  license: Apache-2.0 AND MIT AND BSD-3-Clause AND BSD-2-Clause
  license_file:
    - LICENSE
    - licenses/com_google_absl.txt
    - licenses/com_google_re2.txt
    - licenses/com_google_riegeli.txt
    - licenses/net_sourceforge_half.txt
  dev_url: https://github.com/google/tensorstore

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - traversaro
