{% set version = "0.1.71" %}
# Bazel version is specified upstream, file .bazelversion
# https://github.com/google/tensorstore/blob/master/.bazelversion
{% set bazel_version = "7.5.0" %}

package:
  name: tensorstore
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tensorstore/tensorstore-{{ version }}.tar.gz
  sha256: 5c37c7b385517b568282a7aedded446216335d0cb41187c93c80b53596c92c96
  patches:
    # MacOS needs an extra linker flag so pybind11 finds the python symbols in _tensorstore.so :shrug:
    - patches/pybind11-linkopts.patch  # [osx]
    - patches/0001-Explicitly-select-blake3-for-arm64.patch  # [target_platform == "osx-arm64" or target_platform == "linux-aarch64"]
    - patches/0002-Explicitly-select-blake3-for-ppc64.patch  # [target_platform == "linux-ppc64le"]

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    # Keep bazel listed twice here to help the migrators track dependencies
    - bazel
    - bazel {{ bazel_version }}
    - bazel-toolchain
    - python                              # [target_platform != build_platform]
    - cross-python_{{ target_platform }}  # [target_platform != build_platform]
    - numpy                               # [target_platform != build_platform]
    - pybind11                            # [target_platform != build_platform]
    - pybind11-abi                        # [target_platform != build_platform]
    - zlib                                # [target_platform != build_platform]
  host:
    - pip
    - python
    - wheel
    - setuptools
    - setuptools-scm
    - numpy
    # we use openssl instead of boringssl
    - openssl
    - bzip2
    - blosc
    - libcurl
    - libjpeg-turbo
    - libpng
    - libwebp
    - lz4
    - liblzma-devel
    - zlib
    - libprotobuf
    # unvendored
    - pybind11
    - pybind11-abi
    # Use the one from https://github.com/google/tensorstore/blob/master/third_party/com_github_nlohmann_json/workspace.bzl
    - nlohmann_json 3.11.3
    - libavif
    # needs to be built with bazel
    # https://github.com/abseil/abseil-cpp/blob/ee0ebda/FAQ.md#what-is-abi-and-why-dont-you-recommend-using-a-pre-compiled-version-of-abseil
    # - abseil-cpp
  run:
    - ml_dtypes
    - python

test:
  imports:
    - tensorstore
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tensorstore/
  summary: Read and write large, multi-dimensional arrays
  license: Apache-2.0 AND MIT AND BSD-3-Clause AND BSD-2-Clause
  license_file:
    - LICENSE
    - licenses/com_google_absl.txt
    - licenses/com_google_re2.txt
    - licenses/com_google_riegeli.txt
    - licenses/net_sourceforge_half.txt
  dev_url: https://github.com/google/tensorstore

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - traversaro
